
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.cdirecciones;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int parentesisC = 10;
  public static final int id = 3;
  public static final int coma = 11;
  public static final int resta = 8;
  public static final int parentesisA = 9;
  public static final int suma = 5;
  public static final int multiplicacion = 6;
  public static final int decimal = 4;
  public static final int EOF = 0;
  public static final int division = 7;
  public static final int entero = 2;
  public static final int error = 1;
  public static final int igual = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "entero",
  "id",
  "decimal",
  "suma",
  "multiplicacion",
  "division",
  "resta",
  "parentesisA",
  "parentesisC",
  "coma",
  "igual"
  };
}

